#inspiration: https://gist.github.com/rishitells/3c4536131819cff4eba2c8ab5bbb4570
# build improvements from https://maciejz.dev/gitlab-ci-cd-series-building-angular-application/

# Container image to use for all jobs.
# Best-practice: use a specific version rather than "latest"
image: node:20.18-bullseye

stages:
  - lint
  - build
  - build-img
  - test
  - release
  - deploy

# Run these jobs only when commits are pushed to main and staging
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

default:
  cache:  # Cache modules in between jobs for the same branch if package-lock.json file changes
    key: 
      prefix: $CI_COMMIT_REF_NAME
      files:
        - server/package-lock.json
        - client/package-lock.json
    paths:
    #.npm is a cache directory that contains packages already downloaded. npm will lookup packages in .npm first when installing.
      - server/.npm/
      - client/.npm
  # run this before every job; will hit the cache first
  before_script:
   # when a script gets long, you should put into a file 
   # in your repo (e.g. ci/setup.sh) and call it here
   # npm ci installs exactly the versions in the package-lock.json, this is important to ensure that testing/production environments match local dev environments
   # Tell npm to cache modules in .npm
   # The --prefer-offline option makes npm avoid fetching a module from the package repository unless it's missing from the cache
   - cd server && npm ci --cache .npm --prefer-offline && cd ../client && npm ci --cache .npm --prefer-offline && cd ..

lint-server:
  stage: lint
  script:
    - cd server && npm run lint
  allow_failure: false

lint-client:
  stage: lint
  script:
    - cd client && npm run lint
  allow_failure: false

build-frontend:
  stage: build
  script:
    - export VITE_GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
    - npm install @rollup/rollup-linux-x64-gnu
    - cd client && npm run build
    - ls
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - client/dist

server-test:
  stage: test
  script:
    - cd server && npm run ci-test
  artifacts:
    when: always
    reports:
      junit:
        - server/junit.xml
  allow_failure: false

client-test:
  stage: test
  script:
    - cd client && npm run test:v8
  coverage: '/All files[^|]*\|[^|]*\|[^|]*\|[^|]*\|\s+([\d\.]+)/'
  artifacts:
    when: always
    paths:
      - client/coverage/junit-report.xml
      - client/coverage/json-report.json
    reports:
      coverage_report:
        coverage_format: cobertura
        path: ./client/coverage/junit-report.xml
      junit: ./client/coverage/json-report.json




# https://learn.microsoft.com/en-us/azure/app-service/deploy-run-package
# https://maciejz.dev/gitlab-ci-cd-series-deploying-angular-application-to-azure-storage-static-app/
# https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli
# https://learn.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli

build-image:
  stage: build-img
  image: docker:28.0.0
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
  # dind starts the docker daemon so we can use docker commands
  services:
    - docker:28.0.0-dind
  dependencies:
    - build-frontend
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script: []
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t ${IMAGE_TAG} . --build-arg artifact=true
    - docker push ${IMAGE_TAG}

config-dev:
  stage: deploy
  image:  mcr.microsoft.com/azure-cli
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
      when: never
  variables:
    #the zip file that was created
    RELEASE_FILE: release-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA.zip
  before_script:
    - "az login --allow-no-subscriptions --service-principal -u $AZ_SP_ID -p $AZ_SP_SECRET --tenant $AZ_TENANT"
  script:
    #set env variables on Azure
    - "az webapp config appsettings set --resource-group $RESOURCE_GROUP_NAME --name $APP_NAME-dev --settings ATLAS_URI=$ATLAS_URI"
    - "az webapp config appsettings set --resource-group $RESOURCE_GROUP_NAME --name $APP_NAME-dev --settings AZURE_SAS=$AZURE_SAS"
    - "az webapp config appsettings set --resource-group $RESOURCE_GROUP_NAME --name $APP_NAME-dev --settings AZURE_BLOB_CONTAINER=$AZURE_BLOB_CONTAINER"
    - "az webapp config appsettings set --resource-group $RESOURCE_GROUP_NAME --name $APP_NAME-dev --settings AZURE_STORAGE_ACCOUNT=$AZURE_STORAGE_ACCOUNT"
    - "az webapp config appsettings set --resource-group $RESOURCE_GROUP_NAME --name $APP_NAME-dev --settings GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID"
    - "az webapp config appsettings set --resource-group $RESOURCE_GROUP_NAME --name $APP_NAME-dev --settings GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET"
    - "az webapp config appsettings set --resource-group $RESOURCE_GROUP_NAME --name $APP_NAME-dev --settings SECRET=$SECRET"

deploy-dev:
  stage: deploy
  image: docker:28.0.0
  dependencies:
    - build-image
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
      when: never
  # dind starts the docker daemon so we can use docker commands
  services:
    - docker:28.0.0-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    DOCKER_TAG: craftersden.azurecr.io/webapp/dev-deployment
  before_script: []
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker pull ${IMAGE_TAG}
    - echo $ACR_PASSWD | docker login -u $ACR_USER --password-stdin $ACR_SERVER
    - docker tag ${IMAGE_TAG} ${DOCKER_TAG}
    - docker push ${DOCKER_TAG}

config-prod:
  stage: deploy
  image:  mcr.microsoft.com/azure-cli
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - if: $CI_COMMIT_TAG
  before_script:
    - "az login --allow-no-subscriptions --service-principal -u $AZ_SP_ID -p $AZ_SP_SECRET --tenant $AZ_TENANT"
  script:
    #set env variables on Azure
    - "az webapp config appsettings set --resource-group $RESOURCE_GROUP_NAME --name $APP_NAME --settings ATLAS_URI=$ATLAS_URI"
    - "az webapp config appsettings set --resource-group $RESOURCE_GROUP_NAME --name $APP_NAME --settings AZURE_SAS=$AZURE_SAS"
    - "az webapp config appsettings set --resource-group $RESOURCE_GROUP_NAME --name $APP_NAME --settings AZURE_BLOB_CONTAINER=$AZURE_BLOB_CONTAINER"
    - "az webapp config appsettings set --resource-group $RESOURCE_GROUP_NAME --name $APP_NAME --settings AZURE_STORAGE_ACCOUNT=$AZURE_STORAGE_ACCOUNT"
    - "az webapp config appsettings set --resource-group $RESOURCE_GROUP_NAME --name $APP_NAME --settings GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID"
    - "az webapp config appsettings set --resource-group $RESOURCE_GROUP_NAME --name $APP_NAME --settings GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET"
    - "az webapp config appsettings set --resource-group $RESOURCE_GROUP_NAME --name $APP_NAME --settings SECRET=$SECRET"

deploy-prod:
  stage: deploy
  image: docker:28.0.0
  dependencies:
    - build-image
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - if: $CI_COMMIT_TAG
  # dind starts the docker daemon so we can use docker commands
  services:
    - docker:28.0.0-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    DOCKER_TAG: craftersden.azurecr.io/webapp/prod-deployment
  before_script: []
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker pull ${IMAGE_TAG}
    - echo $ACR_PASSWD | docker login -u $ACR_USER --password-stdin $ACR_SERVER
    - docker tag ${IMAGE_TAG} ${DOCKER_TAG}
    - docker push ${DOCKER_TAG}
